// angular/src/app/components/gallery/gallery.component.ts
import {Component, OnInit} from '@angular/core';
import {User} from "../../api/models/user";
import {ContextService} from "../../services/context-service";
import {PaintingsService} from "../../api/services/paintings.service";
import {Painting} from "../../api/models/painting";
import {ActivatedRoute, Params, Router} from "@angular/router";
import {PaintingsParametersResponse} from "../../api/models";
import {RangeModel} from "../range/range.component";

@Component({
  selector: 'app-gallery',
  templateUrl: './gallery.component.html',
  styleUrls: ['./gallery.component.scss']
})
export class GalleryComponent implements OnInit {

  paintings: Painting[];

  parameters: PaintingsParametersResponse;

  genres = ['Abstract', 'Still life', 'Landscape', 'Portrait', 'Genre art', 'Historical', 'Animalism', 'Nude'];

  filteredGenres: string[] = [];

  filteredWidth: RangeModel = {};

  filteredHeight: RangeModel = {};

  filteredPrice: RangeModel = {};

  filteredUserId: string;

  user: User;

  page = 1;

  limit = 12;

  count: number;

  constructor(private contextService: ContextService, private paintingService: PaintingsService, private router: Router,
              private route: ActivatedRoute) {
  }

  ngOnInit() {
    this.user = this.contextService.getCurrentUser();
    this.getFiltersFromUrl();
    this.getParameters();
    this.getPaintings();
  }

  getFiltersFromUrl() {
    if (this.route.snapshot.queryParams.genres) {
      this.filteredGenres = (this.route.snapshot.queryParams.genres + '').split(',');
    }
    if (this.route.snapshot.queryParams.widthFrom) {
      this.filteredWidth.value1 = +this.route.snapshot.queryParams.widthFrom;
    }
    if (this.route.snapshot.queryParams.widthTo) {
      this.filteredWidth.value2 = +this.route.snapshot.queryParams.widthTo;
    }
    if (this.route.snapshot.queryParams.heightFrom) {
      this.filteredHeight.value1 = +this.route.snapshot.queryParams.heightFrom;
    }
    if (this.route.snapshot.queryParams.heightTo) {
      this.filteredHeight.value2 = +this.route.snapshot.queryParams.heightTo;
    }
    if (this.route.snapshot.queryParams.priceFrom) {
      this.filteredPrice.value1 = +this.route.snapshot.queryParams.priceFrom;
    }
    if (this.route.snapshot.queryParams.priceTo) {
      this.filteredPrice.value2 = +this.route.snapshot.queryParams.priceTo;
    }
    if (this.route.snapshot.queryParams.userId) {
      this.filteredUserId = this.route.snapshot.queryParams.userId;
    }
  }

  getParameters() {
    this.paintingService.getParameters().subscribe(response => {
      this.parameters = response;
    });
  }

  getPaintings() {
    this.paintingService.getAllPaintings(this.getQueryParams()).subscribe(response => {
      this.paintings = response.paintings;
      this.count = response.count;
    });
  }

  setFilteredGenres(genres: string[]) {
    this.filteredGenres = genres;
  }

  setFilteredWidth(range: RangeModel) {
    this.filteredWidth = range;
  }

  setFilteredHeight(range: RangeModel) {
    this.filteredHeight = range;
  }

  setFilteredPrice(range: RangeModel) {
    this.filteredPrice = range;
  }

  getQueryParams() {
    const queryParams: Params = { };
    queryParams.page = this.page;
    queryParams.limit = this.limit;
    if (this.filteredGenres && this.filteredGenres.length > 0) {
      queryParams.genres = this.filteredGenres.join(',');
    }
    if (this.filteredWidth && this.filteredWidth.value1) {
      queryParams.widthFrom = this.filteredWidth.value1;
    }
    if (this.filteredWidth && this.filteredWidth.value2) {
      queryParams.widthTo = this.filteredWidth.value2;
    }
    if (this.filteredHeight && this.filteredHeight.value1) {
      queryParams.heightFrom = this.filteredHeight.value1;
    }
    if (this.filteredHeight && this.filteredHeight.value2) {
      queryParams.heightTo = this.filteredHeight.value2;
    }
    if (this.filteredPrice && this.filteredPrice.value1) {
      queryParams.priceFrom = this.filteredPrice.value1;
    }
    if (this.filteredPrice && this.filteredPrice.value2) {
      queryParams.priceTo = this.filteredPrice.value2;
    }
    if (this.filteredUserId) {
      queryParams.userId = this.filteredUserId;
    }
    return queryParams;
  }

  refresh() {
    // to add query params to url
    this.router.navigate(
      [],
      {
        relativeTo: this.route,
        queryParams: this.getQueryParams()
      });
    // update
    this.getPaintings();

  }

  changePageOrLimit(event) {
    console.log(event);
    this.limit = event.pageSize;
    this.page = event.pageIndex + 1;
    this.refresh();
  }

  clearFilters() {
    window.location.search = '';
  }

}

<div class="gallery">
  <div class="filters" *ngIf="parameters">
    <button class="filter-button" mat-raised-button [matMenuTriggerFor]="genresPopup"
            [matBadge]="this.filteredGenres.length" [matBadgeHidden]="this.filteredGenres.length === 0"
            [matBadgeColor]="'accent'">
      Genres
    </button>
    <button class="filter-button" mat-raised-button [matMenuTriggerFor]="sizesPopup" [matBadge]="'!'"
            [matBadgeColor]="'accent'"
            [matBadgeHidden]="!(this.filteredWidth.value1 || this.filteredWidth.value2 || this.filteredHeight.value1 || this.filteredHeight.value2)">
      Sizes
    </button>
    <button class="filter-button" mat-raised-button [matMenuTriggerFor]="pricePopup" [matBadge]="'!'"
            [matBadgeHidden]="!(this.filteredPrice.value1 || this.filteredPrice.value2)" [matBadgeColor]="'accent'">
      Price
    </button>
    <button class="filter-button" mat-button (click)="refresh()">
      <span>Apply</span>
    </button>
    <button class="filter-button" mat-button (click)="clearFilters()">
      <span>Clear</span>
    </button>
    <mat-menu #genresPopup>
      <div class="filter-popup" (click)="$event.stopPropagation()" (keydown)="$event.stopPropagation()">
        <app-checkbox-group
          [vertical]="true"
          [selectedItems]="filteredGenres"
          [items]="genres"
          (changeEvent)="setFilteredGenres($event)">
        </app-checkbox-group>
      </div>
    </mat-menu>
    <mat-menu #sizesPopup>
      <div class="filter-popup" (click)="$event.stopPropagation()" (keydown)="$event.stopPropagation()">
        <app-range
          [name]="'Width'"
          [placeholder1]="'from ' + parameters.minWidth + 'cm'"
          [placeholder2]="'to ' + parameters.maxWidth + 'cm'"
          [value]="filteredWidth"
          (changeEvent)="setFilteredWidth($event)">
        </app-range>
        <app-range
          [name]="'Height'"
          [placeholder1]="'from ' + parameters.minHeight + 'cm'"
          [placeholder2]="'to ' + parameters.maxHeight + 'cm'"
          [value]="filteredHeight"
          (changeEvent)="setFilteredHeight($event)">
        </app-range>
      </div>
    </mat-menu>
    <mat-menu #pricePopup>
      <div class="filter-popup" (click)="$event.stopPropagation()" (keydown)="$event.stopPropagation()">
        <app-range
          [name]="'Price'"
          [placeholder1]="'from ' + parameters.minPrice + ' BYN'"
          [placeholder2]="'to ' + parameters.maxPrice + ' BYN'"
          [value]="filteredPrice"
          (changeEvent)="setFilteredPrice($event)">
        </app-range>
      </div>
    </mat-menu>
  </div>
  <div class="items">
    <div class="item" *ngFor="let item of paintings">
      <app-painting-card [painting]="item"></app-painting-card>
    </div>
  </div>
  <div class="paginator">
    <mat-paginator
      [length]="count"
      [pageSize]="limit"
      [pageSizeOptions]="[6, 12, 18]"
      (page)="changePageOrLimit($event)">
    </mat-paginator>
  </div>
</div>

// react-typescript/src/components/Gallery.tsx
import React from 'react';
import {apiService} from "../api";
import {Painting} from "../api/";
import '../styles/gallery.scss';
import PaintingCard from "./PaintingCard";
import Pagination from '@material-ui/lab/Pagination';


type GalleryProps = {};
type GalleryState = { paintings?: Array<Painting>, count?: number, totalPages?: number };

class Gallery extends React.Component<GalleryProps, GalleryState> {

    page = 1;

    limit = 12;

    constructor(props: any) {
        super(props);
        this.state = {};
    }

    async componentDidMount() {
        await this.getPaintings();
    }

    async getPaintings() {
        const response = (await apiService.getAllPaintings(...this.getQueryParams())).data;
        console.log(response);
        this.setState({
            paintings: response.paintings,
            count: response.count,
            totalPages: response.totalPages
        })
    }

    getQueryParams() {
        const queryParams = [this.page, this.limit];
        // if (this.filteredGenres && this.filteredGenres.length > 0) {
        //     queryParams.genres = this.filteredGenres.join(',');
        // }
        // if (this.filteredWidth && this.filteredWidth.value1) {
        //     queryParams.widthFrom = this.filteredWidth.value1;
        // }
        // if (this.filteredWidth && this.filteredWidth.value2) {
        //     queryParams.widthTo = this.filteredWidth.value2;
        // }
        // if (this.filteredHeight && this.filteredHeight.value1) {
        //     queryParams.heightFrom = this.filteredHeight.value1;
        // }
        // if (this.filteredHeight && this.filteredHeight.value2) {
        //     queryParams.heightTo = this.filteredHeight.value2;
        // }
        // if (this.filteredPrice && this.filteredPrice.value1) {
        //     queryParams.priceFrom = this.filteredPrice.value1;
        // }
        // if (this.filteredPrice && this.filteredPrice.value2) {
        //     queryParams.priceTo = this.filteredPrice.value2;
        // }
        // if (this.filteredUserId) {
        //     queryParams.userId = this.filteredUserId;
        // }
        return queryParams;
    }

    changePage(event: React.ChangeEvent<unknown>, value: number) {
        this.page = value;
        this.refresh();
    }

    refresh() {
        // to add query params to url
        // this.router.navigate(
        //     [],
        //     {
        //         relativeTo: this.route,
        //         queryParams: this.getQueryParams()
        //     });
        // update
        this.getPaintings();
    }

    render() {
        return (
            <div className="gallery">
                <div className="items">
                    {this.state.paintings?.map(painting => {
                        return <div className="item" key={painting?.name}><PaintingCard painting={painting}/></div>;
                    })}
                </div>
                <div className="paginator">
                    <Pagination count={this.state.totalPages} onChange={(event, page) => this.changePage(event, page)}/>
                </div>
            </div>
        );
    }
}

export default Gallery;
