// client/src/app/components/painting-card/painting-card.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-painting-card',
  templateUrl: './painting-card.component.html',
  styleUrls: ['./painting-card.component.scss']
})
export class PaintingCardComponent implements OnInit {

  @Input()
  src: string;

  @Input()
  name: string;

  @Input()
  author: string;

  @Input()
  price: number;

  constructor() { }

  ngOnInit() {
  }

}

<mat-card class="painting-card">
  <img mat-card-image [src]="src | safeHtml" [alt]="name">
  <mat-card-content class="content">
    <div class="left">
      <div class="name">{{name}}</div>
      <div class="author">{{author}}</div>
    </div>
    <div class="right">
      {{price + ' BYN'}}
    </div>
  </mat-card-content>
</mat-card>

// react-typescript/src/components/PaintingCard.tsx
import React from "react";
import {Painting} from "../api/";
import '../styles/painting-card.scss';
import Card from '@material-ui/core/Card';
import CardActionArea from '@material-ui/core/CardActionArea';
import CardContent from '@material-ui/core/CardContent';
import CardMedia from '@material-ui/core/CardMedia';

type PaintingCardProps = {painting?: Painting};
type PaintingCardState = {};
class PaintingCard extends React.Component<PaintingCardProps, PaintingCardState> {

    painting: Painting;

    constructor(props: any) {
        super(props);
        this.painting = props.painting;
    }

    render() {
        return (
            <Card className="painting-card">
                <CardActionArea>
                    <CardMedia component="img" alt={this.painting?.name} height="300" src={this.painting?.image.data}/>
                </CardActionArea>
                <CardContent className="content">
                    <div className="left">
                        <div className="name">{this.painting.name}</div>
                        <div className="author">{this.painting.author}</div>
                    </div>
                    <div className="right">
                        {this.painting.price + ' BYN'}
                    </div>
                </CardContent>
            </Card>
        );
    }
}

export default PaintingCard;
