// angular-ngrx/src/app/components/painting-editor/painting-editor.component.ts
import { Component, OnInit } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup, Validators } from "@angular/forms";
import { PaintingsService } from "../../api/services/paintings.service";
import { ActivatedRoute, Router } from "@angular/router";
import { User } from 'src/app/api/models';
import { selectCurrentUser } from 'src/app/store/selectors/system.selectors';
import { AppState } from 'src/app/store/state/app.state';
import { Store } from '@ngrx/store';

@Component({
  selector: 'app-painting-editor',
  templateUrl: './painting-editor.component.html',
  styleUrls: ['./painting-editor.component.scss']
})
export class PaintingEditorComponent implements OnInit {

  form: UntypedFormGroup = new UntypedFormGroup({});

  genres = ['Abstract', 'Still life', 'Landscape', 'Portrait', 'Genre art', 'Historical', 'Animalism', 'Nude'];

  images: File[] = [];

  imagesSrc: string[] = [];

  loading: boolean;

  paintingId: string;

  currentUser: User;

  constructor(private formBuilder: UntypedFormBuilder, private paintingService: PaintingsService, private router: Router,
    private route: ActivatedRoute, private store: Store<AppState>) {
  }

  ngOnInit() {
    this.store.select(selectCurrentUser).subscribe(currentUser => {
      this.currentUser = currentUser;
    });
    this.paintingId = this.route.snapshot.params.id;
    if (this.paintingId) {
      this.loading = true;
      this.paintingService.getPainting(this.paintingId).subscribe(response => {
        const painting = response.painting;
        this.form = this.formBuilder.group({
          name: [painting.name, [Validators.required]],
          author: [painting.author, [Validators.required]],
          genres: [painting.genres, [Validators.required]],
          height: [painting.height, [Validators.required]],
          width: [painting.width, [Validators.required]],
          price: [painting.price, [Validators.required]],
          description: [painting.description]
        });
        this.imagesSrc = [painting.image.data];
        this.loading = false;
      });
    } else {
      this.form = this.formBuilder.group({
        name: [null, [Validators.required]],
        author: [null, [Validators.required]],
        genres: [[], [Validators.required]],
        height: [null, [Validators.required]],
        width: [null, [Validators.required]],
        price: [null, [Validators.required]],
        description: [null]
      });
    }
  }

  getErrorMessage(controlName: string, fieldName?: string): string {
    let errorText = '';
    if (!fieldName) {
      fieldName = controlName;
    }
    const control = this.form.controls[controlName];
    if (control && control.errors) {
      if (control.hasError('required')) {
        errorText = `Please fill in '${fieldName}' field`;
      }
      if (control.hasError('required') && controlName === 'genres') {
        errorText = 'Please select at least one genre';
      }
    }

    return errorText;
  }

  setImages(event) {
    this.images = event;
  }

  setGenres(genres) {
    this.form.controls.genres.setValue(genres);
  }

  checkInteger(event) {
    return event.charCode !== 46;
  }

  checkNumberFormat(event, formControlName: string) {
    const correctedValue = event.target.value.replace(/([^\d]*)(\d*(\.\d{0,2})?)(.*)/, '$2');
    event.target.value = correctedValue;
    this.form.controls[formControlName].setValue(correctedValue, { emitEvent: false });
  }

  deleteImages() {
    this.images = [];
  }

  isFormValid(): boolean {
    let isFormValid = true;
    if (this.form.invalid) {
      for (let inner in this.form.controls) {
        this.form.get(inner).markAsTouched();
      }
      isFormValid = false;
    }
    return isFormValid;
  }

  submit() {
    if (!this.isFormValid()) {
      return;
    }
    const paintingDto = {
      name: this.form.controls.name.value,
      author: this.form.controls.author.value,
      userId: this.currentUser.id,
      genres: this.form.controls.genres.value.join('+'),
      width: +this.form.controls.width.value,
      height: +this.form.controls.height.value,
      price: +this.form.controls.price.value,
      description: this.form.controls.description.value
    } as any;
    if (this.images[0]) {
      paintingDto.image = this.images[0];
    }
    if (this.paintingId) {
      paintingDto.paintingId = this.paintingId;
      this.paintingService.updatePainting(paintingDto).subscribe(response => {
        this.router.navigate(['/gallery/' + this.paintingId]);
      });
    } else {
      this.paintingService.uploadPainting(paintingDto).subscribe(response => {
        this.router.navigate(['/gallery/' + response.painting.id]);
      });
    }

  }
}

<div class="painting-editor" *ngIf="!(loading$ | async)">
  <form class="form" [formGroup]="form">

    <app-image-uploader
      [fileSrcs]="imagesSrc"
      [multiUpload]="true"
      (onUpload)="setImages($event)"
      (onDelete)="deleteImages()"
    >
    </app-image-uploader>
    <div class="field-error">
      {{images.length === 0 && form.touched && !paintingId? 'Please upload an image' : ''}}
    </div>

    <mat-form-field>
      <input matInput placeholder="Name" formControlName="name"/>
      <mat-error>{{getErrorMessage('name')}}</mat-error>
    </mat-form-field>

    <mat-form-field>
      <input matInput placeholder="Author" formControlName="author"/>
      <mat-error>{{getErrorMessage('author')}}</mat-error>
    </mat-form-field>

    <app-checkbox-group [items]="genres" [selectedItems]="getSelectedGenres()" (changeEvent)="setGenres($event)"></app-checkbox-group>
    <div class="field-error">
      {{form.get('genres').invalid && form.get('genres').touched ? getErrorMessage('genres') : ''}}
    </div>

    <mat-form-field>
      <input matInput type="number" min="0" max="2147483647" (keyup)="checkNumberFormat($event, 'height')" (keypress)="checkInteger($event)" placeholder="Height (cm)" formControlName="height"/>
      <mat-error>{{getErrorMessage('height')}}</mat-error>
    </mat-form-field>

    <mat-form-field>
      <input matInput type="number" min="0" max="2147483647" (keyup)="checkNumberFormat($event, 'width')" (keypress)="checkInteger($event)" placeholder="Width (cm)" formControlName="width"/>
      <mat-error>{{getErrorMessage('width')}}</mat-error>
    </mat-form-field>

    <mat-form-field>
      <input matInput type="number" min="0" max="2147483647" (keyup)="checkNumberFormat($event, 'price')"  placeholder="Price (BYN)" formControlName="price"/>
      <mat-error>{{getErrorMessage('price')}}</mat-error>
    </mat-form-field>

    <mat-form-field>
      <textarea  style="min-height: 80px"  matInput cdkTextareaAutosize placeholder="Description" formControlName="description" maxlength="500"></textarea>
      <mat-error>{{getErrorMessage('description')}}</mat-error>
    </mat-form-field>

  </form>
  <button class="submit" mat-flat-button color="primary" (click)="submit()">Submit</button>

</div>
<mat-progress-bar [mode]="'indeterminate'" *ngIf="loading$ | async"></mat-progress-bar>

// react-typescript/src/components/painting-editor/PaintingEditor.tsx
import React from "react";
import {Painting as PaintingModel, User as UserModel} from "../../api";
import * as yup from "yup";
import {paintingService, userService} from "../../services/api";
import {from} from "rxjs";
import ImageUploader from "../shared/ImageUploader";
import {Button, FormControl, FormHelperText, InputLabel, MenuItem, Select, TextField} from "@material-ui/core";
import {genres, roles} from "../../constants";
import {Formik} from "formik";
import storageService from "../../services/storage";
import CheckboxGroup from "../shared/CheckboxGroup";
import '../../styles/painting-editor/painting-editor.scss';

type PaintingEditorProps = { match: any, history: any };
type PaintingEditorState = { painting: PaintingModel, images: File[], imagesSrc: string[], loading: boolean };

class PaintingEditor extends React.Component<PaintingEditorProps, PaintingEditorState> {

    validationSchema = yup.object({
        name: yup.string().required('Name is required'),
        author: yup.string().required('Author is required'),
        genres: yup.array().required('At least one genre must be specified'),
        height: yup.number().required('Height is required'),
        width: yup.number().required('Width is required'),
        price: yup.string().required('Price is required'),
        description: yup.string().nullable(true)
    });

    paintingId: string;

    constructor(props: any) {
        super(props);
        this.state = {
            painting: {
                name: undefined,
                author: undefined,
                genres: [],
                height: undefined,
                width: undefined,
                price: undefined,
                description: undefined,
                image: undefined,
                userId: undefined
            },
            images: [],
            imagesSrc: [],
            loading: true
        };
    }

    componentDidMount(): void {
        this.paintingId = this.props.match.params.id;
        if (this.paintingId) {
            from(paintingService.getPainting(this.paintingId)).subscribe(response => {
                this.setState({painting: response.data.painting, loading: false, imagesSrc: [response.data.painting.image.data]});
            });
        } else {
            this.setState({loading: false});
        }
    }

    setImage(image) {
        this.setState({images: image})
    }

    setSelectedGenres(genres: string[]) {
        let painting = this.state.painting;
        painting.genres = genres;
        this.setState({painting});
    }

    submit(values) {
        if (this.paintingId) {
            // paintingDto.paintingId = this.paintingId;
            // this.paintingService.updatePainting(paintingDto).subscribe(response => {
            //     this.router.navigate(['/gallery/' + this.paintingId]);
            // });
            from(paintingService.updatePainting(this.paintingId, values.name, values.author, this.state.painting.userId,
                values.genres.join('+'), values.height, values.width, values.price, this.state.images[0] || undefined, values.description)).subscribe(response => {

            });
        } else {
            from(paintingService.uploadPainting(this.state.images[0], values.name, values.author, storageService.getUser().id,
                values.genres.join('+'), values.height, values.width, values.price, values.description)).subscribe(response => {
                this.props.history.push('/gallery/' + response.data.painting.id);
            });
        }

    }

    render() {
        return (
            <div className="painting-editor">
                {!this.state.loading &&
                <Formik
                    initialValues={this.state.painting}
                    validationSchema={this.validationSchema}
                    enableReinitialize={true}
                    onSubmit={(values) => this.submit(values)}>
                    {
                        formik => (
                            <form className="form" onSubmit={formik.handleSubmit}>
                                <ImageUploader oldFileSrcs={this.state.imagesSrc} onUpload={(image) => this.setImage(image)}/>
                                <div className="field-error">
                                    {this.state.images.length === 0 && formik.touched.image && !this.paintingId ? 'Please upload an image' : ''}
                                </div>
                                <TextField
                                    className="input" fullWidth name="name" label="Name"
                                    value={formik.values.name}
                                    onChange={formik.handleChange}
                                    onBlur={formik.handleBlur}
                                    error={formik.touched.name && Boolean(formik.errors.name)}
                                    helperText={formik.touched.name && formik.errors.name}
                                />
                                <TextField
                                    className="input" fullWidth name="author" label="Author"
                                    value={formik.values.author}
                                    onChange={formik.handleChange}
                                    onBlur={formik.handleBlur}
                                    error={formik.touched.author && Boolean(formik.errors.author)}
                                    helperText={formik.touched.author && formik.errors.author}
                                />
                                <div className="checkbox-group-wrapper">
                                    <CheckboxGroup
                                        items={genres}
                                        value={this.state.painting.genres}
                                        onSelectedItemsChange={(genres) => this.setSelectedGenres(genres)}
                                    />
                                    <div className="field-error">
                                        {this.state.painting.genres.length === 0 && formik.touched.genres ? 'Please select at least one genre' : ''}
                                    </div>
                                </div>
                                <TextField
                                    className="input" fullWidth name="height" label="Height"
                                    value={formik.values.height}
                                    onChange={formik.handleChange}
                                    onBlur={formik.handleBlur}
                                    error={formik.touched.height && Boolean(formik.errors.height)}
                                    helperText={formik.touched.height && formik.errors.height}
                                />
                                <TextField
                                    className="input" fullWidth name="width" label="Width"
                                    value={formik.values.width}
                                    onChange={formik.handleChange}
                                    onBlur={formik.handleBlur}
                                    error={formik.touched.width && Boolean(formik.errors.width)}
                                    helperText={formik.touched.width && formik.errors.width}
                                />
                                <TextField
                                    className="input" fullWidth name="price" label="Price"
                                    value={formik.values.price}
                                    onChange={formik.handleChange}
                                    onBlur={formik.handleBlur}
                                    error={formik.touched.price && Boolean(formik.errors.price)}
                                    helperText={formik.touched.price && formik.errors.price}
                                />
                                <TextField
                                    className="input" fullWidth name="description" label="Description"
                                    value={formik.values.description}
                                    onChange={formik.handleChange}
                                    onBlur={formik.handleBlur}
                                    multiline={true}
                                    rows={4}
                                    error={formik.touched.description && Boolean(formik.errors.description)}
                                    helperText={formik.touched.description && formik.errors.description}
                                />
                                <Button className={'button primary submit'} color="inherit"
                                        variant="contained"
                                        type="submit">
                                    Submit
                                </Button>
                            </form>
                        )
                    }
                </Formik>
                }
            </div>
        );
    }
}

export default PaintingEditor;
