// react-typescript/src/components/painting/Painting.tsx
import React from "react";
import '../../styles/painting/painting.scss';
import {Card} from "@material-ui/core";
import CardMedia from "@material-ui/core/CardMedia";
import {paintingService, userService} from "../../services/api";
import {mergeMap} from "rxjs/operators";
import {from} from "rxjs";
import {Painting as PaintingModel} from "../../api/";
import {User as UserModel} from "../../api/";
import storageService from "../../services/storage";
import {Link} from "react-router-dom";
import EditIcon from '@material-ui/icons/Edit';
import DeleteIcon from '@material-ui/icons/Delete';

type PaintingProps = { match: any };
type PaintingState = { painting: PaintingModel, user: UserModel };

class Painting extends React.Component<PaintingProps, PaintingState> {

    paintingId: string;

    currentUser: UserModel;

    constructor(props: any) {
        super(props);
        this.state = {
            painting: null,
            user: null
        }
    }

    componentDidMount(): void {
        this.paintingId = this.props.match.params.id;
        this.currentUser = storageService.getUser();
        from(paintingService.getPainting(this.paintingId)).pipe(mergeMap(response => {
            this.setState({painting: response.data.painting});
            return from(userService.getUser(this.state.painting.userId));
        })).subscribe(response => {
            this.setState({user: response.data.user});
        });
    }

    delete() {

    }

    render() {
        return (
            <>{
                this.state.painting && this.state.user &&
                <div className="painting">
                    <Card>
                        <CardMedia component="img" alt={this.state.painting.name} src={this.state.painting.image.data}/>
                    </Card>
                    <div className="details-wrapper">
                        <Card className="details">
                            {
                                (this.state.painting.userId === this.currentUser?.id || this.currentUser?.role === 'Admin') &&
                                <div className="actions">
                                    <Link to={'/painting-editor/' + this.paintingId}><EditIcon/></Link>
                                    <DeleteIcon onClick={() => this.delete()}/>
                                </div>
                            }
                            <div className="field title">{this.state.painting.name}</div>
                            <div className="field">
                                <div className="label">Author:</div>
                                <div className="value">{this.state.painting.author}</div>
                            </div>
                            <div className="field">
                                <div className="label">Genre:</div>
                                <div className="value">{this.state.painting.genres.join(', ')}</div>
                            </div>
                            <div className="field">
                                <div className="label">Size:</div>
                                <div
                                    className="value">{this.state.painting.height + ' x ' + this.state.painting.width + ' (cm)'}</div>
                            </div>
                            <div className="field">
                                <div className="label">Description:</div>
                                <div className="value">{this.state.painting.description}</div>
                            </div>
                        </Card>
                        <Card className="details">
                            <div className="price">{this.state.painting.price + ' BYN'}</div>
                        </Card>
                        <Card className="details">
                            <div className="field subtitle">Contacts</div>
                            {this.state.user.phone &&
                            <div className="field">
                                <div className="label">Phone number:</div>
                                <div className="value">{this.state.user.phone}</div>
                            </div>}
                            <div className="field">
                                <div className="label">E-mail:</div>
                                <div className="value">{this.state.user.email}</div>
                            </div>
                        </Card>
                    </div>
                </div>
            }</>
        );
    }
}

/*
* <div class="painting">
  <ng-container *ngIf="painting && user">
    <div class="details-wrapper">
      <mat-card class="details">
        <div class="actions" *ngIf="painting.userId === user.id || user.role === 'Admin'">
          <mat-icon [routerLink]="'/painting-editor/' + painting.id">edit</mat-icon>
          <mat-icon (click)="delete()">delete</mat-icon>
        </div>
      </mat-card>

    </div>
  </ng-container>
</div>
*/
export default Painting;

// angular-ngrx/src/app/components/painting/painting.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute, Router} from "@angular/router";
import {PaintingsService} from "../../api/services/paintings.service";
import {Painting} from "../../api/models/painting";
import {User} from "../../api/models/user";
import {mergeMap} from "rxjs/operators";
import {UsersService} from "../../api/services/users.service";
import { MatDialog } from "@angular/material/dialog";
import {ContextService} from "../../services/context-service";

@Component({
  selector: 'app-painting',
  templateUrl: './painting.component.html',
  styleUrls: ['./painting.component.scss']
})
export class PaintingComponent implements OnInit {

  painting: Painting;

  user: User;

  currentUser: User;

  constructor(private route: ActivatedRoute, private paintingService: PaintingsService, private userService: UsersService,
              public dialog: MatDialog, private router: Router, private context: ContextService) {
  }

  ngOnInit() {
    this.currentUser = this.context.getCurrentUser();
    const paintingId = this.route.snapshot.params.id;
    this.paintingService.getPainting(paintingId).pipe(mergeMap(response => {
      this.painting = response.painting;
      return this.userService.getUser(this.painting.userId);
    })).subscribe(response => {
      this.user = response.user;
    });
  }

  getImageSrc() {
    if (this.painting) {
      return this.painting.image.data;
    }
  }

  delete() {
    const dialogRef = this.dialog.open(PaintingDeletionConfirmationComponent);
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.paintingService.deletePainting(this.painting.id).subscribe(response => {
          this.router.navigate(['/']);
        });
      }
    });
  }

}

@Component({
  selector: 'app-painting-deletion-confirmation',
  templateUrl: './painting-deletion-confirmation.html',
})
export class PaintingDeletionConfirmationComponent {}

<div class="painting">
  <ng-container *ngIf="painting">
    <mat-card class="image">
      <img mat-card-image [src]="getImageSrc() | safeHtml" [alt]="painting.name">
    </mat-card>
    <div class="details-wrapper">
      <mat-card class="details">
        <div class="actions" *ngIf="painting.userId === (currentUser$ | async)?.id || (currentUser$ | async)?.role === 'Admin'">
          <mat-icon [routerLink]="'/painting-editor/' + painting.id">edit</mat-icon>
          <mat-icon (click)="delete()">delete</mat-icon>
        </div>
        <div class="field title">{{painting.name}}</div>
        <div class="field">
          <div class="label">Author:</div>
          <div class="value">{{painting.author}}</div>
        </div>
        <div class="field">
          <div class="label">Genre:</div>
          <div class="value">{{painting.genres.join(', ')}}</div>
        </div>
        <div class="field">
          <div class="label">Size:</div>
          <div class="value">{{painting.height + ' x ' + painting.width + ' (cm)'}}</div>
        </div>
        <div class="field">
          <div class="label">Description:</div>
          <div class="value">{{painting.description}}</div>
        </div>
      </mat-card>
      <mat-card class="details">
        <div class="price">{{painting.price + ' BYN'}}</div>
      </mat-card>
      <mat-card class="details">
        <div class="field subtitle">Contacts</div>
        <div class="field" *ngIf="(user$ | async)?.phone">
          <div class="label">Phone number:</div>
          <div class="value">{{(user$ | async)?.phone}}</div>
        </div>
        <div class="field">
          <div class="label">E-mail:</div>
          <div class="value">{{(user$ | async)?.email}}</div>
        </div>
      </mat-card>

    </div>
  </ng-container>
</div>
